name : Python CI

on:
  push:
    branches: [ main ]


jobs:
  build-test:
    runs-on : ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4


    - name: settingup python for app
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: install dependencies
      run : |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run the test
      run: pytest -v     

